const days = [
  { title: 'Trung tâm & chợ đêm', stops: [
    ['08:00', 'Đến Đà Lạt', 'Gửi hành lý · thuê xe máy', 48.2, 53.7], ['08:30', 'Bánh căn + xíu mại', 'Bữa sáng thật ấm bụng', 48.2, 53.7], ['09:30', 'Vườn hoa thành phố', 'Dạo chơi · chụp ảnh', 44, 46.5], ['11:00', 'Ga Đà Lạt', 'Check-in ga cổ', 31.5, 29], ['14:00', 'Khách sạn', 'Nhận phòng · nghỉ ngơi', 48.2, 53.7], ['15:30', 'Cafe view đồi', 'Ngồi chill 1–1,5 giờ', 68, 78], ['17:00', 'Hồ Xuân Hương + Lâm Viên', 'Đi dạo · ngắm hoàng hôn', 48, 53.5], ['20:00', 'Chợ đêm Đà Lạt', 'Ăn vặt · sữa đậu nóng', 49, 57], ['22:00', 'Về khách sạn', 'Nghỉ ngơi', 48.2, 53.7]
  ]},
  { title: 'Cầu Đất & Datanla', stops: [
    ['05:00', 'Xuất phát đi Cầu Đất', 'Nhớ mang áo khoác dày', 48.2, 53.7], ['06:00', 'Săn mây · bình minh', 'Thung lũng trong mây', 89.5, 13.5], ['07:30', 'Cafe Cầu Đất', 'Ăn sáng nhẹ · ngắm đồi', 89.5, 13.5], ['09:00', 'Đồi chè Cầu Đất', 'Dạo chơi · chụp ảnh', 72, 27], ['12:00', 'Ăn trưa trung tâm', 'Gà nướng cơm lam', 48.2, 53.7], ['15:00', 'Thác Datanla', 'Tham quan · máng trượt', 72, 80], ['17:00', 'Cafe chill', 'View rừng · hoàng hôn', 68, 78], ['20:30', 'Tự do', 'Acoustic · bar · dạo phố', 49, 57]
  ]},
  { title: 'Chill nhẹ & tạm biệt', stops: [
    ['07:30', 'Ăn sáng', 'Bánh mì xíu mại · bánh căn', 48.2, 53.7], ['08:30', 'Cafe sáng', 'Một giờ thong thả', 68, 78], ['09:30', 'Check-in nhẹ', 'Vườn hoa hoặc Dinh I Bảo Đại', 25, 83.5], ['11:00', 'Dạo trung tâm', 'Mua quà · nghỉ ngơi', 49, 57], ['12:30', 'Ăn trưa', 'Nem nướng · lẩu · cơm nhà', 48.2, 53.7], ['14:00', 'Mua đặc sản', 'Dâu · trà · atiso · mứt', 49, 57], ['15:00', 'Tạm biệt Đà Lạt', 'Lấy hành lý · di chuyển về', 48.2, 53.7]
  ]}
];
const places = [
  ['Hồ Xuân Hương','Hoàng hôn','https://statics.vinpearl.com/da-lat-thuoc-mien-nao-3_1701342243.jpeg'],['Ga Đà Lạt','Nét cổ xưa','https://vietnamtimes.thoidai.com.vn/stores/news_dataimages/2026/052026/08/20/cd56784da29f0aeec24d56b5c8970061.jpg?rt=20260508203426'],['Quảng trường Lâm Viên','Nhịp phố','https://benthanhtourist.com/resize/1060x0/tour/trong-nuoc/da-lat/quang-truong-lam-vien.webp'],['Chợ đêm Đà Lạt','Về khuya','https://cdn.imweb.me/upload/S201612155852461149cae/1b8181cd07b3f.jpg'],['Đồi chè Cầu Đất','Màu xanh','https://dalattrongtim.com/wp-content/uploads/2020/11/20170104091915-doi-che-cau-dat-gody-5.jpg'],['Săn mây Cầu Đất','Bình minh','https://img.360dalat.com/resize/730x-/2022/12/06/khung-canh-cau-go-san-may-cau-dat-c96f.jpg'],['Thác Datanla','Vào rừng','https://dalathappytours.com/images/uploads/nice_wiew_from_datanla_water_fall.jpg'],['Dinh I Bảo Đại','Một thời xưa','https://static.vinwonders.com/production/dinh-bao-dai-da-lat-2.jpg'],['Cafe view đồi','Chill thôi','https://www.bachhoaxanh.com/kinh-nghiem-hay/15-quan-cafe-o-da-lat-view-tuyet-dep-khong-gian-yen-binh-tho-mong-day-lang-man-1342079']
];
const foods = [
  ['Bánh căn + xíu mại','https://datviettour.com.vn/uploads/images/dalat/dac-san/b__nh_c__n_chung.jpeg'],['Bánh mì xíu mại','https://kenh14cdn.com/203336854389633024/2022/6/14/4-1655193265679759427317.jpg'],['Nem nướng','https://static.vinwonders.com/production/quan-an-ngon-da-lat-12.jpg'],['Lẩu gà lá é','https://phetravel.com/uploads/lau-ga-la-e.jpg'],['Lẩu bò','https://img.tripi.vn/cdn-cgi/image/width%3D700%2Cheight%3D700/https%3A/gcs.tripi.vn/public-tripi/tripi-feed/img/485952bOo/anh-mo-ta.png'],['Gà nướng cơm lam','https://down-vn.img.susercontent.com/vn-11134513-7r98o-lsvc2inz9bbt2e%40resize_ss640x400'],['Bánh ướt lòng gà','https://www.vietfuntravel.com.vn/image/data/Da-Lat/quan-an-gan-cho-da-lat/banh-uot-long-ga-da-lat.jpg'],['Bánh tráng nướng','https://galatourist.com/pic/blog/images/vietnam-travel-guide/dalat-travel-guide/what-to-eat-in-dalat/740-banh-trang-nuong.jpg'],['Xắp xắp','https://bazantravel.com/cdn/medias/uploads/22/22224-xap-xap-5-e1510152030935.jpg'],['Sữa đậu nành nóng','https://file3.qdnd.vn/data/images/14/2024/07/24/upload_2217/suasau92135940pm.jpeg?dpi=150&quality=100&w=870']
];
let activeDay = 0, playing = false, timer;
const stopList = document.querySelector('#stopList'), travellers = document.querySelector('#travellers');
function drawStops(day) { activeDay=day; document.querySelectorAll('.day-tabs button').forEach((b,i)=>b.classList.toggle('active',i===day)); stopList.innerHTML=days[day].stops.map((s,i)=>`<article class="stop ${i===0?'active':''}" data-stop="${i}"><div class="stop-time">${s[0]}</div><div><h3>${s[1]}</h3><p>${s[2]}</p></div></article>`).join(''); document.querySelectorAll('.stop').forEach(el=>el.onclick=()=>moveTo(+el.dataset.stop)); moveTo(0,false); }
function moveTo(index, animate=true) { const s=days[activeDay].stops[index]; travellers.style.setProperty('--x',s[3]+'%'); travellers.style.setProperty('--y',s[4]+'%'); document.querySelector('#mapLabel').textContent='Đang ở: '+s[1]; document.querySelector('#mapTime').textContent=s[0]; document.querySelectorAll('.stop').forEach((el,i)=>el.classList.toggle('active',i===index)); if(animate){document.querySelector('#routePath').style.strokeDashoffset='-32';setTimeout(()=>document.querySelector('#routePath').style.strokeDashoffset='0',100)} }
function playJourney(){clearInterval(timer);playing=true;let d=0,i=0;drawStops(0); timer=setInterval(()=>{i++;if(i>=days[d].stops.length){d++;i=0;if(d>=days.length){clearInterval(timer);playing=false;return}drawStops(d)}moveTo(i)},1750)}
document.querySelector('#playTrip').onclick=playJourney;document.querySelector('#restartMap').onclick=playJourney;document.querySelectorAll('.day-tabs button').forEach((b,i)=>b.onclick=()=>{clearInterval(timer);playing=false;drawStops(i)});
document.querySelector('#dayPanels').innerHTML=days.map((day,i)=>`<article class="day-card" data-day="0${i+1}"><p class="eyebrow">Ngày ${i+1}</p><h3>${day.title}</h3><ul class="mini-stops">${day.stops.slice(0,6).map(s=>`<li><b>${s[0]} · ${s[1]}</b><span>${s[2]}</span></li>`).join('')}</ul></article>`).join('');
const placeTemplate=document.querySelector('#placeTemplate'); places.forEach(([name,label,url])=>{const card=placeTemplate.content.cloneNode(true);card.querySelector('img').src=url;card.querySelector('img').alt=name;card.querySelector('span').textContent=label;card.querySelector('h3').textContent=name;document.querySelector('#placeGallery').append(card)});
const template=document.querySelector('#foodTemplate'); foods.forEach(([name,url],i)=>{const card=template.content.cloneNode(true);card.querySelector('.food-number').textContent=String(i+1).padStart(2,'0');card.querySelector('h3').textContent=name;const image=card.querySelector('.food-image');image.innerHTML='';image.setAttribute('aria-label',name);image.style.backgroundImage=`linear-gradient(135deg,rgba(26,66,52,.25),rgba(196,111,69,.15)), url('${url}')`;document.querySelector('#foodGrid').append(card)});
drawStops(0);
