const places = [
  ['Hồ Xuân Hương','Hoàng hôn','https://statics.vinpearl.com/da-lat-thuoc-mien-nao-3_1701342243.jpeg'],['Ga Đà Lạt','Nét cổ xưa','https://vietnamtimes.thoidai.com.vn/stores/news_dataimages/2026/052026/08/20/cd56784da29f0aeec24d56b5c8970061.jpg?rt=20260508203426'],['Quảng trường Lâm Viên','Nhịp phố','https://benthanhtourist.com/resize/1060x0/tour/trong-nuoc/da-lat/quang-truong-lam-vien.webp'],['Chợ đêm Đà Lạt','Về khuya','https://cdn.imweb.me/upload/S201612155852461149cae/1b8181cd07b3f.jpg'],['Đồi chè Cầu Đất','Màu xanh','https://dalattrongtim.com/wp-content/uploads/2020/11/20170104091915-doi-che-cau-dat-gody-5.jpg'],['Săn mây Cầu Đất','Bình minh','https://img.360dalat.com/resize/730x-/2022/12/06/khung-canh-cau-go-san-may-cau-dat-c96f.jpg'],['Thác Datanla','Vào rừng','https://dalathappytours.com/images/uploads/nice_wiew_from_datanla_water_fall.jpg'],['Dinh I Bảo Đại','Một thời xưa','https://static.vinwonders.com/production/dinh-bao-dai-da-lat-2.jpg'],['Cafe view đồi','Chill thôi','https://www.bachhoaxanh.com/kinh-nghiem-hay/15-quan-cafe-o-da-lat-view-tuyet-dep-khong-gian-yen-binh-tho-mong-day-lang-man-1342079']
];
const foods = [
  ['Bánh căn + xíu mại','https://datviettour.com.vn/uploads/images/dalat/dac-san/b__nh_c__n_chung.jpeg'],['Bánh mì xíu mại','https://kenh14cdn.com/203336854389633024/2022/6/14/4-1655193265679759427317.jpg'],['Nem nướng','https://static.vinwonders.com/production/quan-an-ngon-da-lat-12.jpg'],['Lẩu gà lá é','https://phetravel.com/uploads/lau-ga-la-e.jpg'],['Lẩu bò','https://img.tripi.vn/cdn-cgi/image/width%3D700%2Cheight%3D700/https%3A/gcs.tripi.vn/public-tripi/tripi-feed/img/485952bOo/anh-mo-ta.png'],['Gà nướng cơm lam','https://down-vn.img.susercontent.com/vn-11134513-7r98o-lsvc2inz9bbt2e%40resize_ss640x400'],['Bánh ướt lòng gà','https://www.vietfuntravel.com.vn/image/data/Da-Lat/quan-an-gan-cho-da-lat/banh-uot-long-ga-da-lat.jpg'],['Bánh tráng nướng','https://galatourist.com/pic/blog/images/vietnam-travel-guide/dalat-travel-guide/what-to-eat-in-dalat/740-banh-trang-nuong.jpg'],['Xắp xắp','https://bazantravel.com/cdn/medias/uploads/22/22224-xap-xap-5-e1510152030935.jpg'],['Sữa đậu nành nóng','https://file3.qdnd.vn/data/images/14/2024/07/24/upload_2217/suasau92135940pm.jpeg?dpi=150&quality=100&w=870']
];
const hotel=[11.9401,108.4385], lake=[11.9417,108.4375], station=[11.9417,108.4582], flower=[11.9477,108.4429], market=[11.9406,108.4382], caudat=[11.8663,108.5538], tea=[11.8695,108.5532], datanla=[11.8878,108.4701], dinh=[11.9240,108.4702], cafe=[11.9235,108.4284];
const days = [
 {title:'Trung tâm & chợ đêm',stops:[['08:00','Đến Đà Lạt','Gửi hành lý · thuê xe máy',hotel],['08:30','Bánh căn + xíu mại','Bữa sáng thật ấm bụng',market],['09:30','Vườn hoa thành phố','Dạo chơi · chụp ảnh',flower],['11:00','Ga Đà Lạt','Check-in ga cổ',station],['14:00','Khách sạn','Nhận phòng · nghỉ ngơi',hotel],['15:30','Cafe view đồi','Ngồi chill 1–1,5 giờ',cafe],['17:00','Hồ Xuân Hương + Lâm Viên','Đi dạo · ngắm hoàng hôn',lake],['20:00','Chợ đêm Đà Lạt','Ăn vặt · sữa đậu nóng',market],['22:00','Về khách sạn','Nghỉ ngơi',hotel]]},
 {title:'Cầu Đất & Datanla',stops:[['05:00','Xuất phát đi Cầu Đất','Nhớ mang áo khoác dày',hotel],['06:00','Săn mây · bình minh','Thung lũng trong mây',caudat],['07:30','Cafe Cầu Đất','Ăn sáng nhẹ · ngắm đồi',caudat],['09:00','Đồi chè Cầu Đất','Dạo chơi · chụp ảnh',tea],['12:00','Ăn trưa trung tâm','Gà nướng cơm lam',hotel],['15:00','Thác Datanla','Tham quan · máng trượt',datanla],['17:00','Cafe chill','View rừng · hoàng hôn',cafe],['20:30','Tự do','Acoustic · bar · dạo phố',market]]},
 {title:'Chill nhẹ & tạm biệt',stops:[['07:30','Ăn sáng','Bánh mì xíu mại · bánh căn',market],['08:30','Cafe sáng','Một giờ thong thả',cafe],['09:30','Dinh I Bảo Đại','Check-in nhẹ',dinh],['11:00','Dạo trung tâm','Mua quà · nghỉ ngơi',market],['12:30','Ăn trưa','Nem nướng · lẩu · cơm nhà',hotel],['14:00','Mua đặc sản','Dâu · trà · atiso · mứt',market],['15:00','Tạm biệt Đà Lạt','Lấy hành lý · di chuyển về',hotel]]}
];
let activeDay=0, map, routeLine, groupMarker, mapLayers=[], currentLatLng, playTimer;
const stopList=document.querySelector('#stopList');
const groupIcon=L.divIcon({className:'',html:'<div class="traveller-marker"><i>♂</i><i>♀</i><i>♂</i><i>♀</i></div>',iconSize:[88,30],iconAnchor:[44,15]});
function bootMap(){const stage=document.querySelector('#mapStage');stage.innerHTML='<div id="realMap"></div>';map=L.map('realMap',{zoomControl:false,attributionControl:true}).setView(hotel,12);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);groupMarker=L.marker(hotel,{icon:groupIcon,zIndexOffset:1000}).addTo(map);renderMapDay();}
function pinIcon(symbol,current=false){return L.divIcon({className:'',html:`<div class="real-pin ${current?'current':''}"><span>${symbol}</span></div>`,iconSize:[31,39],iconAnchor:[15,39]})}
function photoFor(name){if(name.includes('Ga'))return places[1][2];if(name.includes('Hồ')||name.includes('Lâm Viên'))return places[0][2];if(name.includes('Chợ')||name.includes('Ăn sáng')||name.includes('Mua đặc sản'))return places[3][2];if(name.includes('Vườn hoa'))return places[0][2];if(name.includes('Cầu Đất')||name.includes('mây'))return places[5][2];if(name.includes('chè'))return places[4][2];if(name.includes('Datanla'))return places[6][2];if(name.includes('Dinh'))return places[7][2];if(name.includes('Cafe'))return places[8][2];return places[0][2]}
function popupHtml(s){return `<article class="place-popup"><img src="${photoFor(s[1])}" alt="${s[1]}" referrerpolicy="no-referrer"><div><small>${s[0]} · NGÀY ${activeDay+1}</small><h3>${s[1]}</h3><p>${s[2]}</p></div></article>`}
function renderMapDay(){if(!map)return;mapLayers.forEach(x=>map.removeLayer(x));mapLayers=[];const stops=days[activeDay].stops;const seen=new Set();stops.forEach((s,i)=>{const key=s[3].join(',');if(seen.has(key))return;seen.add(key);const marker=L.marker(s[3],{icon:pinIcon(i===0?'✦':'●')}).bindPopup(popupHtml(s),{maxWidth:290}).addTo(map);marker.on('click',()=>focusStop(i));mapLayers.push(marker)});const coords=stops.map(s=>s[3]);routeLine=L.polyline(coords,{color:'#e97748',weight:6,opacity:.9,dashArray:'12 10',lineCap:'round'}).addTo(map);mapLayers.push(routeLine);map.fitBounds(routeLine.getBounds(),{padding:[45,45],maxZoom:13});currentLatLng=stops[0][3];groupMarker.setLatLng(currentLatLng);loadRoadRoute(coords);}
async function loadRoadRoute(coords){try{const compact=coords.filter((p,i)=>i===0||p[0]!==coords[i-1][0]||p[1]!==coords[i-1][1]);const query=compact.map(p=>`${p[1]},${p[0]}`).join(';');const res=await fetch(`https://router.project-osrm.org/route/v1/driving/${query}?overview=full&geometries=geojson`);const json=await res.json();if(json.routes?.[0]?.geometry?.coordinates){const route=json.routes[0].geometry.coordinates.map(([lng,lat])=>[lat,lng]);routeLine.setLatLngs(route);map.fitBounds(routeLine.getBounds(),{padding:[35,35],maxZoom:13})}}catch{ /* Keep the direct route if live routing is unavailable. */ }}
function flyGroup(target,duration=2200){const from=groupMarker.getLatLng(),start=performance.now();map.panTo(target,{animate:true,duration:duration/1000,noMoveStart:true});function frame(now){const p=Math.min(1,(now-start)/duration),e=p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2;groupMarker.setLatLng([from.lat+(target[0]-from.lat)*e,from.lng+(target[1]-from.lng)*e]);if(p<1)requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function moveTo(index,animate=true){const s=days[activeDay].stops[index];document.querySelector('#mapLabel').textContent='Đang ở: '+s[1];document.querySelector('#mapTime').textContent=s[0];document.querySelectorAll('.stop').forEach((el,i)=>el.classList.toggle('active',i===index));if(animate)flyGroup(s[3]);else groupMarker.setLatLng(s[3]);currentLatLng=s[3];}
function focusStop(index){const s=days[activeDay].stops[index];moveTo(index,false);map.flyTo(s[3],16,{duration:1.1});setTimeout(()=>L.popup({maxWidth:290,autoPan:true}).setLatLng(s[3]).setContent(popupHtml(s)).openOn(map),850)}
function drawStops(day){activeDay=day;document.querySelectorAll('.day-tabs button').forEach((b,i)=>b.classList.toggle('active',i===day));stopList.innerHTML=days[day].stops.map((s,i)=>`<article class="stop ${i===0?'active':''}" data-stop="${i}"><div class="stop-time">${s[0]}</div><div><h3>${s[1]}</h3><p>${s[2]}</p></div></article>`).join('');document.querySelectorAll('.stop').forEach(el=>el.onclick=()=>focusStop(+el.dataset.stop));renderMapDay();moveTo(0,false)}
function playJourney(){clearInterval(playTimer);let day=0,index=0;drawStops(day);map.setZoom(13);playTimer=setInterval(()=>{index++;if(index>=days[day].stops.length){day++;index=0;if(day>=days.length){clearInterval(playTimer);return}drawStops(day);map.setZoom(13)}moveTo(index)},2850)}
document.querySelector('#playTrip').onclick=playJourney;document.querySelector('#restartMap').onclick=playJourney;document.querySelectorAll('.day-tabs button').forEach((b,i)=>b.onclick=()=>{clearInterval(playTimer);drawStops(i)});
document.querySelector('#dayPanels').innerHTML=days.map((day,i)=>`<article class="day-card" data-day="0${i+1}"><p class="eyebrow">Ngày ${i+1}</p><h3>${day.title}</h3><ul class="mini-stops">${day.stops.slice(0,6).map(s=>`<li><b>${s[0]} · ${s[1]}</b><span>${s[2]}</span></li>`).join('')}</ul></article>`).join('');
const placeTemplate=document.querySelector('#placeTemplate');places.forEach(([name,label,url])=>{const card=placeTemplate.content.cloneNode(true),img=card.querySelector('img');img.src=url;img.alt=name;img.referrerPolicy='no-referrer';card.querySelector('span').textContent=label;card.querySelector('h3').textContent=name;document.querySelector('#placeGallery').append(card)});
const foodTemplate=document.querySelector('#foodTemplate');foods.forEach(([name,url],i)=>{const card=foodTemplate.content.cloneNode(true),img=card.querySelector('img');card.querySelector('.food-number').textContent=String(i+1).padStart(2,'0');card.querySelector('h3').textContent=name;img.src=url;img.alt=name;img.onerror=()=>img.parentElement.classList.add('image-error');document.querySelector('#foodGrid').append(card)});
bootMap();drawStops(0);
